service_name: HelloWorld
cpu_limit: 1000m
memory_limit: 1200Mi

predeploy: 
  command: ["bin/predeploy.sh"]
setup: 
  command: ["bin/setup.sh"]

routes:
  port: 3000
  subdomain: app
  path: /

volumes:
  - name: image-volume
    storage: 5Gi
    mount_path: /mnt/pipelines
    storage_class: standard-retain

jobs:
  sidekiq:
    cmd: bundle exec sidekiq
    cpu_limit: 1000m
    cpu_request: 200m
    cpu_per: WORKER_CPU_SCALE_FACTOR
    memory_limit: 2500Mi
    memory_request: 1600Mi
    liveness_command: pgrep -f sidekiq -c
    #liveness_port:
    #liveness_url:

